### PR TITLE
IVcurve automated analysis

### PR DESCRIPTION
**Pull request by elrama-**
Implemented the automated analysis for IV curves on Vespa.

Includes auto-fitting of resistance.

Gonna add more comments afterwards. DO NOT MERGE IT YET(code police will probably complain)!

### CODE REVIEW

**Comment by AdriaanRol** [comment]
@elrama- can you give an update on the status of this?

**Comment by AdriaanRol** [comment]
@elrama- could you give a status update on this?

**Comment by elrama-** [comment]
no status for now @AdriaanRol

**Comment by AdriaanRol** [comment]
@elrama- I am closing this pull request as it is more than 7! months old.  I don't believe this will still be fixed.

**Pull request closed without merging**
