### PR TITLE
SSRO_analysis and n-qubit on-off

### PR DESCRIPTION
**Pull request by antsr**
This is part 1 of splitting up pull request #330 

Changes proposed in this pull request:
- improve the structure of SSRO analysis
- improve info on SSRO analysis plots
- add option to do an additional preselection pulse before state preparation to remove thermal population
- add generic n-qubit on-off awg sweep function.

There is still room for improvement in SSRO analysis I think (in terms of structure and speed), these are the changes I made to make it usable for us.

Example plot generated by SSRO analysis:
histograms-masked

@AdriaanRol

### CODE REVIEW

**Comment by AdriaanRol** [comment]
I'll review this now as it the SSRO analysis is leading to problems in the M18 branch (and this could potentially fix it).

**Comment by AdriaanRol** [comment]
I'll merge once the tests pass (which should be within 10  mins).

**Comment by AdriaanRol** [comment]
@antsr somehow the tests are not triggered after I updated your branch with the master. I guess this is because the branch is not on the main repository but on your fork. Could you let me know if you are able to manually trigger it?

**Comment by antsr** [comment]
Don't know why the tests did not trigger, but I see that the tests passed after merging to master.

**Comment by AdriaanRol** [comment]
@antsr Yep, I decided to bypass the tests as I knew it was OK before updating master into it.

**Pull request merged**
