### PR TITLE
Contribution guidelines

### LINKED ISSUE #172: Contributing guidelines
Update the contributing guidelines according to templates by Jacob and a new branching paradigm

### PR DESCRIPTION
**Pull request by AdriaanRol**
Closes #172 . Branching structure needs to be discussed in the upcoming meeting.

### CODE REVIEW

**Comment by AdriaanRol** [comment]
@everyone, I've added everyone who is currently actively using PycQED as a reviewer as I would like to have input on this.

**Comment by antsr** [comment]
I think that it would be appropriate to also mention PEP 8 and maybe some documentation guidelines that one should follow when contributing.

**Comment by AdriaanRol** [comment]
Two more things should be added to this guideline, 
- Weekly code cleanup todo 
- Branching policy concerning special project branches

**Comment by AdriaanRol** [comment]
@everyone, there is now a proposal here for the branching structure that is consistent with what we've been doing the last couple of weeks. I'd appreciate it if someone could review this. 

@antsr , I've included your suggestions in the requirements for a PR to be merged.

**Comment by fluthi** [comment]
I think this is in good agreement with what we have discussed on the first code meeting, and also what the current practice is. 
So far, I have never used supporting branches, and I also don't necessarily see why they are important - you can also just cherry-pick from your project branch. Or is it then not possible to have the changes as pull requests?
Besides that, it might be good to include the Git code snippet for pulling the master in a project branch - this will make it easier for new users to get started.

**Comment by AdriaanRol** [comment]
@fluthi 
- the point of the supporting branch is exactly that, you would first create a supporting branch from the master and then put your changes you want to merge into the master on that branch. This can be either done by working directly on that branch or by cherry-picking as you describe. You can then create a pull request for that branch. 
-  good point, I will add that snippet to the weekly code cleanup moment description.

**Comment by nathanlangford** [comment]
Broadly speaking, I can follow most of this.  Here are some comments:

1) "We consider _origin/master_ to be the main branch where the source code of HEAD always reflects a production-ready state."
vs "We consider the project branch to be the main branch where the source code of HEAD always reflects a state with the latest changes used in the project."
-- How can both of these be "main branches"?  I find this language confusing.

2) "travis test suites" -- what are you supposed to do about this?  This is jargon.

3) "all reasonable issues raised by codacy must be resolved" -- is this something that happens automatically?  how does one see "codacy" issues?

4) ' These are repository dependent and prefixed with "Cat: '
This formatting doesn't seem consistent with "type:" and "prio:" - is there a typo here?

**Comment by AdriaanRol** [comment]
@nathanlangford , @fluthi I think I have addressed your issues in the latest commit. Let me know if this is the case (and hit the checkbox approve if it does).

**Pull request merged**
