### PR TITLE
[WIP] PR to monitor whether cleanup breaks anything

### PR DESCRIPTION
**Pull request by wvlothuizen**
The purpose of this PR is to get rid of unused stuff, in a reversible way. Unused code makes it more difficult to maintain the code base, and reduces code coverage since for many old pieces of code no tests exist.

### CODE REVIEW

**Comment by wvlothuizen** [comment]
Got an OK from ETH/Christoph Hellings

**Comment by MiguelSMoreira** [comment]
After bringing develop up to date with our latest developments, I would like to merge this pull request into develop and delete this branch. Can I proceed @wvlothuizen ?

**Comment by wvlothuizen** [comment]
yes, let's proceed

**Review by MiguelSMoreira — APPROVED** [review]
Seems good!

**Pull request merged**
