### PR TITLE
Enabled the assembler to merge two consecutive wait instructions.

### PR DESCRIPTION
**Pull request by gtaifu**

### CODE REVIEW

**Comment by AdriaanRol** [comment]
Hi Xiang, 

You have requested a review, could you give a short summary of what you want me to look at/what are the features that were added and what should I test? 
I think testing this takes ~10 mins so it should be quite simple. 

Let me know.

**Comment by gtaifu** [comment]
@AdriaanRol 

The functionality added is like the title name. Now the assembler could merge two wait instructions into one. That's it.

**Comment by AdriaanRol** [comment]
OK, I'll approve the PR after I've tested it. 

Also noted there was something else added (file not found error) but I guess that's not the main functionality.

**Comment by gtaifu** [comment]
Exactly, that are not the main functionality, which make the code better.

**Pull request merged**
