### PR TITLE
imported files from starmon and updated qx_client for error handling

### PR DESCRIPTION
**Pull request by stanvn**
Changes proposed in this pull request:
- New demonstration helpers in `/pycqed/measurement/demonstration-helpers` 
- Updated qx_client with error handling
- Updated qasm loader with some replace options
- Updated quantumsim and qx detectors and sweep function to work with the demonstration helpers
- Created qasm loader test

@AdriaanRol

### CODE REVIEW

**Comment by kel85uk** [comment]
I will take this over from here.

**Comment by AdriaanRol** [comment]
@kel85uk any updates on this? I assume you are still working on this.

**Comment by kel85uk** [comment]
@AdriaanRol Yes, I am planning to do the merge using the branch feature/qumis_infinity_helpers

**Comment by AdriaanRol** [comment]
@kel85uk If I understand correctly that means that this PR can be closed. 
Feel free to reopen if I am mistaken.

**Pull request closed without merging**
