### PR TITLE
Periodic merge of develop into master

### PR DESCRIPTION
**Pull request by AdriaanRol**
Periodic merge. 
Reasons to merge 
- Upcoming update to OpenQL v0.5.3 
- Fix broken test related to CZ simulation on master. 

Requesting @elrama- to review as he is not currently working on develop.

### CODE REVIEW

**Comment by slavoutich** [comment]
As a comment: you use sometimes `'''docstring'''`, while PEPs specify double brackets (`"""docstring"""`). This might confuse some code editors, I guess.

**Comment by AdriaanRol** [comment]
@slavoutich , thanks for pointing that out. I'll use double brackets from now on.

**Comment by AdriaanRol** [comment]
@elrama- , gentle reminder

**Comment by elrama-** [comment]
I have been checking it, but still not finished on my check-up. Will give an update in a day.

**Comment by AdriaanRol** [comment]
@elrama- , thanks for the update

**Pull request merged**
