### PR TITLE
Adapt calibration pattern sent from the SHFQA to the CC

### PR DESCRIPTION
**Pull request by jul-sm**
Changes proposed in this pull request:
- adapt SHFQA to CC program to calibrate DIO on CC succesfully

@wvlothuizen

### CODE REVIEW

**Comment by MiniSean** [comment]
@wvlothuizen (@jul-sm), is this pending a verification test?

**Comment by jul-sm** [comment]
Hi @MiniSean. I have a test that calibrates the DIO on the CC when sending calibration codewords from the SHFQA using this adaption. That passes, the calibration is done successfully. I don't know if by verification test you mean something else.

**Comment by MiniSean** [comment]
Hi @jul-sm, great! That is indeed what I meant. In that case we can merge this PR and close the issue for now. If @wvlothuizen is not able to sign off on the review, feel free to add me as a reviewer.

**Comment by jul-sm** [comment]
Hi @MiniSean, thank you!

**Review by MiniSean — APPROVED** [review]
Clear concise change.

- [X] Passes corresponding test.

**Pull request merged**
