### PR TITLE
Feature/lutmanconfig

### LINKED ISSUE #706: Add config for hardcoded ro-lutman settings
If you encounter a bug use the following template.
If you have a feature request feel free to freestyle.

### Addressing issue

- Current Base_RO_lutMan class constructor assumes a hardcoded resonator codeword bit mapper.
- Create *.yaml config file specifically for these code word mapping.
- Add feature where a default config file is generated with default mapping corresponding to the current hardcoded mapping for consistency.

### PR DESCRIPTION
**Pull request by MiniSean**
Fixes #706.

Changes proposed in this pull request:
- Local config file for RO-LutMan bit-mapping.
- Read/Write of .yaml config files.
- Config file defaults to previously hardcoded settings for backwards compatibility
- Add data class structure to store bit-map information
- Add test case coverage for proposed data classes + read/write functionality.

@wvlothuizen good-practice states that at least one other developer should review the changes :)
Thanks in advance!

### CODE REVIEW

**Review by wvlothuizen — APPROVED** [review]
Looks good, a nice step away from hardcoded configuration.

A remark about YAML: OpenQL uses JSON (which apparently is a subset of YAML), for users it might be easier to stick on a single format.

It would be great to at some point merge the OpenQL view of resonator combinations (implied in e.g. https://github.com/DiCarloLab-Delft/PycQED_py3/blob/develop/pycqed/measurement/openql_experiments/config/config_cc_s17_direct_iq.json.in#L22) with that of PycQED

**Comment by MiniSean** [comment]
CI fails due to codecoverage report.

**Comment by MiniSean** [comment]
> A remark about YAML: OpenQL uses JSON (which apparently is a subset of YAML), for users it might be easier to stick on a single format.

JSON would work just as well. I know that YAML is quite flexible in reconstructing class instances from config files.

> It would be great to at some point merge the OpenQL view of resonator combinations (implied in e.g. https://github.com/DiCarloLab-Delft/PycQED_py3/blob/develop/pycqed/measurement/openql_experiments/config/config_cc_s17_direct_iq.json.in#L22) with that of PycQED

That is a good point, let me study how it is implemented in OpenQL. But maybe that is for a separate issue.

**Comment by wvlothuizen** [comment]
Merging this PR, further work can be done later

**Pull request merged**
