### PR TITLE
fix: DSB demodulation scaling with UHFLI

### LINKED ISSUE #275: UHFLI detector scaling
### Steps to reproduce
1. Measure heterodyne spectroscopy with UHFLI, single_sideband_demodulation = True
2. Measure heterodyne spectroscopy with UHFLI, single_sideband_demodulation = False
3. See that the amplitudes differ by a factor of 2.

### Expected behaviour
Regardless of the SSB demodulation setting, the result should be scaled correctly to the amplitude of the measured pulse.

### Actual behaviour
Using double sideband demodulation the returned value is half the amplitude.

### System
**operating system**
Windows 7 64 bit

**PycQED branch**
Proj/Bluefors1 (updated with master)

**PycQED commit**
24841015b457ba38f70ad69752f99cc1577dcf7b

### Labels to be added
type:bug:
prio:medium:
cat:UHFLI:

### PR DESCRIPTION
**Pull request by antsr**
Fixes #275 

Changes proposed in this pull request:
- Change the rotation matrix weights to correctly scale UHFQC output when using double sideband demodulation

@AdriaanRol

### CODE REVIEW

**Comment by antsr** [comment]
I have not yet tested the fix on physical hardware, but it should work.

**Comment by AdriaanRol** [comment]
@antsr , Could you add a comment as to why the factor 2 is needed?

**Comment by antsr** [comment]
The integration weights set up by the UHFQC.prepare_SSB_weight_and_rotation() calculate the integrated result as:
```
out1 = ∑ᵢ ( in1ᵢ cos(ω i / fs) + in2ᵢ sin(ω i / fs) )
out2 = ∑ᵢ ( in1ᵢ sin(ω i / fs) - in2ᵢ cos(ω i / fs) )
```
or in complex form
```
out1 + j out2 = ∑ᵢ (in1ᵢ - j in2ᵢ) exp(j ω i / fs)
```
`ω` is the intermediate angular frequency and `fs` is the sampling frequency, `in1ᵢ` and `in2ᵢ` are the arrays of samples acquired by the UHFQC in channels 1 and 2 and `out1` and `out2` are the weighted integration results.

The formula for UHFQC.prepare_DSB_weight_and_rotation() in the old version is the same, except that the weights corresponding to input channel 2 are zero:
```
out1 + j out2 = ∑ᵢ in1ᵢ exp(j ω i / fs)
```

Now if we apply an ideal signal at the input of the UHFLI
```
in1ᵢ + j in2ᵢ = A exp(j ω i / fs + j ϕ)
```
the output for the SSB case is
```
out1 + j out2 = ∑ᵢ A exp(-j ω i / fs - j ϕ) exp(j ω i / fs) = A N exp(-j ϕ)
```
and in the DSB case:
```
out1 + j out2 = ∑ᵢ A cos(j ω i / fs + j ϕ) exp(j ω i / fs) = 
              = A/2 ∑ᵢ (exp(2 j ω i / fs + j ϕ) + exp(-j ϕ)) = 
              = A N exp(-j ϕ) / 2 + A exp(j ϕ) (1 - exp(2 j ω N / fs)) / (2 - 2 exp(2 j ω / fs))
```
It is clear that in the DSB case the absolute value of `out1 + j out2` is half of that of the SSB case in the big `N` (number of integration samples) limit.

To fix this I doubled the rotation matrix elements (with what the integration results for the two input channels are multiplied) for the DSB case.

**Comment by antsr** [comment]
Also tested on real hardware now and working as expected.

**Pull request merged**
