### PR TITLE
Cz flux arc fix

### PR DESCRIPTION
**Pull request by AdriaanRol**
Radical changes to the CZ flux pulses, made with @FKMalina . 

Please do not merge, this is mostly there so I have access to a convenient diff with develop.

### CODE REVIEW

**Comment by AdriaanRol** [comment]
Everything is implemented, @FKMalina is using it now in experiment. 
I will write some more tests to ensure everything is working as expected and plot some figures below of the plotting methods (that still need to be updated).

**Comment by AdriaanRol** [comment]
Images generated by the flux lutman on demand now. 

image
image

**Comment by fbattistel** [comment]
I've realized that the bug was not affecting the final result because we take the ratio t/scale afterwards

**Comment by AdriaanRol** [comment]
Hi @fbattistel , I'm assuming you are OK with the changes but could you (for the sake of protocol) hit the approve button? 

You can find it in the review changes button in the "files changed" tab. 
screenshot 2018-08-30 13 40 57

Please do not merge yet, this is typically done by whoever opened the pull request (PR).

**Pull request merged**
